name: Build and Publish Wheel on Windows

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境来运行构建任务

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # 选择 Python 版本，3.8 可以根据需要调整

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2019buildtools

      - name: Install other dependencies
        run: |
          pip install -r requirements.txt  # 如果你有其他依赖的话

      - name: Install packaging module
        run: |
          python -m pip install --upgrade pip
          pip install packaging
          #pip install torch==2.6.0 
          # +cu124 -f https://download.pytorch.org/whl/torch_stable.html
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126
          nvcc --version
          
      - name: Set CUDA environment variables
        run: |
          set CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6  # 修改为你的 CUDA 路径
          set PATH=%CUDA_HOME%\bin;%PATH%
          set LIBRARY_PATH=%CUDA_HOME%\libnvvp;%LIBRARY_PATH%
          

          
      - name: Build Wheel
        run: |
          python setup.py bdist_wheel  # 使用 setuptools 来构建 .whl 文件

      - name: Upload Wheel file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: spargeattn-wheel
          path: dist/*.whl  # 上传构建好的 .whl 文件
